---
#/home/manasa/eos-ansible-quick-start/roles/protocol_down/tasks
 - name: Checking if the status is up and link is down
   debug:
     msg : "for the interface {{ item.split(' ')[0] }} status is up and link is down ,either cable is damaged or configuration is wrong "
   with_items: "{{ show.stdout_lines}}"
   when : item | search('up [ ]*down')

